# Exercise 1

### Step 1. Go to [Kaggle]( https://www.kaggle.com/openfoodfacts/world-food-facts)

### Step 2. Download the dataset to your computer and unzip it.

### Step 3. Use the csv file and assign it to a dataframe called food

In [2]:
import pandas as pd
import numpy as np

In [10]:
food = pd.read_csv('products.csv',sep='\t')

C:\Users\EGH\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2717: DtypeWarning: Columns (19,20,24,25,26,28,37,38,39,48) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [17]:
food.head()

,code,url,creator,created_t,created_datetime,last_modified_t,last_modified_datetime,product_name,generic_name,quantity,...,fruits-vegetables-nuts_100g,fruits-vegetables-nuts-estimate_100g,collagen-meat-protein-ratio_100g,cocoa_100g,chlorophyl_100g,carbon-footprint_100g,nutrition-score-fr_100g,nutrition-score-uk_100g,glycemic-index_100g,water-hardness_100g
0,3087,http://world-en.openfoodfacts.org/product/0000...,openfoodfacts-contributors,1474103866,2016-09-17T09:17:46Z,1474103893,2016-09-17T09:18:13Z,Farine de blé noir,NaN,1kg,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4530,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489069957,2017-03-09T14:32:37Z,1489069957,2017-03-09T14:32:37Z,Banana Chips Sweetened (Whole),NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,14.0,14.0,NaN,NaN
2,4559,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489069957,2017-03-09T14:32:37Z,1489069957,2017-03-09T14:32:37Z,Peanuts,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN
3,16087,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489055731,2017-03-09T10:35:31Z,1489055731,2017-03-09T10:35:31Z,Organic Salted Nut Mix,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,12.0,NaN,NaN
4,16094,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489055653,2017-03-09T10:34:13Z,1489055653,2017-03-09T10:34:13Z,Organic Polenta,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
food.describe()

,code,created_t,last_modified_t,cities,allergens_en,no_nutriments,additives_n,ingredients_from_palm_oil_n,ingredients_from_palm_oil,ingredients_that_may_be_from_palm_oil_n,...,fruits-vegetables-nuts_100g,fruits-vegetables-nuts-estimate_100g,collagen-meat-protein-ratio_100g,cocoa_100g,chlorophyl_100g,carbon-footprint_100g,nutrition-score-fr_100g,nutrition-score-uk_100g,glycemic-index_100g,water-hardness_100g
count,7.991200e+04,7.991200e+04,7.991200e+04,0.0,0.0,0.0,77291.000000,77291.000000,0.0,77291.000000,...,25.000000,3.000000,0.0,8.000000,0.0,0.0,61832.000000,61832.000000,0.0,0.0
mean,2.161754e+11,1.486957e+09,1.488082e+09,NaN,NaN,NaN,2.361387,0.000802,NaN,0.034428,...,23.056000,50.666667,NaN,49.500000,NaN,NaN,9.166386,9.147610,NaN,NaN
std,3.546818e+13,1.222171e+07,7.567132e+06,NaN,NaN,NaN,2.746427,0.028311,NaN,0.185214,...,37.051924,42.735621,NaN,27.918248,NaN,NaN,9.095288,9.105755,NaN,NaN
min,1.000000e+01,1.332445e+09,1.386940e+09,NaN,NaN,NaN,0.000000,0.000000,NaN,0.000000,...,0.000000,25.000000,NaN,24.000000,NaN,NaN,-13.000000,-13.000000,NaN,NaN
25%,2.150006e+10,1.489061e+09,1.489061e+09,NaN,NaN,NaN,0.000000,0.000000,NaN,0.000000,...,0.000000,26.000000,NaN,30.000000,NaN,NaN,1.000000,1.000000,NaN,NaN
50%,4.119005e+10,1.489071e+09,1.489072e+09,NaN,NaN,NaN,2.000000,0.000000,NaN,0.000000,...,0.000000,27.000000,NaN,34.000000,NaN,NaN,10.000000,10.000000,NaN,NaN
75%,4.790051e+10,1.489094e+09,1.489094e+09,NaN,NaN,NaN,3.000000,0.000000,NaN,0.000000,...,37.400000,63.500000,NaN,72.000000,NaN,NaN,16.000000,16.000000,NaN,NaN
max,7.089699e+15,1.505691e+09,1.505691e+09,NaN,NaN,NaN,29.000000,1.000000,NaN,3.000000,...,100.000000,100.000000,NaN,100.000000,NaN,NaN,40.000000,40.000000,NaN,NaN

### Step 4. See the first 5 entries

In [13]:
food[:5]

,code,url,creator,created_t,created_datetime,last_modified_t,last_modified_datetime,product_name,generic_name,quantity,...,fruits-vegetables-nuts_100g,fruits-vegetables-nuts-estimate_100g,collagen-meat-protein-ratio_100g,cocoa_100g,chlorophyl_100g,carbon-footprint_100g,nutrition-score-fr_100g,nutrition-score-uk_100g,glycemic-index_100g,water-hardness_100g
0,3087,http://world-en.openfoodfacts.org/product/0000...,openfoodfacts-contributors,1474103866,2016-09-17T09:17:46Z,1474103893,2016-09-17T09:18:13Z,Farine de blé noir,NaN,1kg,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4530,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489069957,2017-03-09T14:32:37Z,1489069957,2017-03-09T14:32:37Z,Banana Chips Sweetened (Whole),NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,14.0,14.0,NaN,NaN
2,4559,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489069957,2017-03-09T14:32:37Z,1489069957,2017-03-09T14:32:37Z,Peanuts,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN
3,16087,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489055731,2017-03-09T10:35:31Z,1489055731,2017-03-09T10:35:31Z,Organic Salted Nut Mix,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,12.0,NaN,NaN
4,16094,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489055653,2017-03-09T10:34:13Z,1489055653,2017-03-09T10:34:13Z,Organic Polenta,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Step 5. What is the number of observations in the dataset?

In [51]:
food.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 79912 entries, 0 to 79911
Columns: 163 entries, code to water-hardness_100g
dtypes: float64(109), int64(3), object(51)
memory usage: 99.4+ MB

### Step 6. What is the number of columns in the dataset?

In [52]:
food.shape[1]

163

### Step 7. Print the name of all the columns.

In [38]:
food.columns

Index(['code', 'url', 'creator', 'created_t', 'created_datetime',
       'last_modified_t', 'last_modified_datetime', 'product_name',
       'generic_name', 'quantity',
       ...
       'fruits-vegetables-nuts_100g', 'fruits-vegetables-nuts-estimate_100g',
       'collagen-meat-protein-ratio_100g', 'cocoa_100g', 'chlorophyl_100g',
       'carbon-footprint_100g', 'nutrition-score-fr_100g',
       'nutrition-score-uk_100g', 'glycemic-index_100g',
       'water-hardness_100g'],
      dtype='object', length=163)

### Step 8. What is the name of 105th column?

In [44]:
nombreColumnas = food.columns
nombreColumnas[105]

'-fructose_100g'

### Step 9. What is the type of the observations of the 105th column?

In [47]:
food.ix[:,105]

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
5       NaN
6       NaN
7       NaN
8       NaN
9       NaN
10      NaN
11      NaN
12      NaN
13      NaN
14      NaN
15      NaN
16      NaN
17      NaN
18      NaN
19      NaN
20      NaN
21      NaN
22      NaN
23      NaN
24      NaN
25      NaN
26      NaN
27      NaN
28      NaN
29      NaN
         ..
79882   NaN
79883   NaN
79884   NaN
79885   NaN
79886   NaN
79887   NaN
79888   NaN
79889   NaN
79890   NaN
79891   NaN
79892   NaN
79893   NaN
79894   NaN
79895   NaN
79896   NaN
79897   NaN
79898   NaN
79899   NaN
79900   NaN
79901   NaN
79902   NaN
79903   NaN
79904   NaN
79905   NaN
79906   NaN
79907   NaN
79908   NaN
79909   NaN
79910   NaN
79911   NaN
Name: -fructose_100g, Length: 79912, dtype: float64

### Step 10. How is the dataset indexed?

In [45]:
food.index

RangeIndex(start=0, stop=79912, step=1)

Step 11. What is the product name of the 19th observation?

In [49]:
food.ix[19,'product_name']

'Organic Oat Groats'